#ifndef OO_DEFS_H
#define OO_DEFS_H

#include <amtl/am-cxx.h>

KE_CONSTEXPR int OO_VERSION = 110;

namespace oo
{
	KE_CONSTEXPR int IDENTIFIER_LEN	= 24u;

	KE_CONSTEXPR int OO_CONTINUE 	= 0;
	KE_CONSTEXPR int OO_SUPERCEDE 	= 1;
	KE_CONSTEXPR int OO_BREAK 		= 2;

	KE_CONSTEXPR int OO_STRING_EX 	= -2;
	KE_CONSTEXPR int OO_STRING		= -1;
	KE_CONSTEXPR int OO_BYREF		= 0;
	KE_CONSTEXPR int OO_FLOAT		= 1;
	KE_CONSTEXPR int OO_CELL		= 1;
}

#endif // OO_DEFS_H